### ISSUE TITLE
Menu Walker - Parent Non-Link Detection

### ISSUE THREAD

**Issue by briankelleher** [aberkow/a11y-menu#20]
Right now, in the menu walker, in order to set a top level item you must have absolutely nothing in the link field for a menu item.  "#" will trigger it being a link, where "" will not.

Can we add support for having "#" in the link field, since this is the default for a blank link/custom link in WordPress?

**Comment by aberkow** [comment]
that's a really good idea. I'll see where to add a check against that.

**Comment by aberkow** [comment]
5ee65e0bf7f9 resolves this issue. 

both the js package and WP walker look check if the link for the menu item is either `#` or `http(s)://#` and turn those links into buttons.
