### ISSUE TITLE
Namespace (Suggested) SCSS

### ISSUE THREAD

**Issue by briankelleher** [aberkow/a11y-menu#30]
The SCSS snippet from (icon-styles.scss) are good, however they apply to ALL nav items.  Suggest namespacing a11y-menu somehow with a class or an ID.  Might be related to instructions that require you to include an ID when initializing the menu in JS.

**Comment by briankelleher** [comment]
Also, might be a good idea to comment/specify which style applies to menu open and which to menu close.  You can sorta guess via the SCSS but it should be more clear or at least documented. (:

**Comment by aberkow** [comment]
that's a good idea. I added `am-` to all the css class names so this might break some styling, but should be easy to change.

for the `<ul>` itself, I think that adding a similar `am-` to the id will work. then the selector for the icon styles can be `ul[id^='am-']`. does that make sense?

**Comment by briankelleher** [comment]
That makes sense.

My original issue pertained to just a single parent element having an ID or class or something, but if you see a need for all of them to be namespaced, that probably has merit as to reduce the chance of collision - however it is going to make the code a bit larger and less simple.  Up to you.

**Comment by aberkow** [comment]
I think I'm going to keep them namespaced because I feel like I won't get confused with which elements I'm working with for css/js. doing this is going to break a few things so I'll also update the readme. 

fortunately it fails nicely and falls back to a menu with hover-able elements.

**Comment by aberkow** [comment]
resolved in f75c43963eb37163e63d50f4977cd06e6b4b94e6
