### ISSUE TITLE
Provide Custom Events to Hook Into

### ISSUE THREAD

**Issue by briankelleher** [aberkow/a11y-menu#39]
A fantastic addition would be the ability to hook into certain events happening on the JavaScript side of things, such as when a submenu is toggled, focused, etc, per your lib.  That way, we can manipulate the menu on these events without having to dig into the source code for this project or forking.

I found a decent answer below where the user simply triggers an event after the necessary functions were run.  Could be a good starting point:

https://stackoverflow.com/questions/20761612/how-do-i-check-if-a-data-attribute-changes

**Comment by aberkow** [comment]
this is what I've come up with so far. ab92986833d737f4b965969a07dffc1edd8a05b4

it creates a custom event which (right now) adds a class to top level items when their submenus are open. I'm sure it could do other things as well. it doesn't really handle hovering right now, but that might not be as much of an issue. I need to do more testing on that.
