### ISSUE TITLE
Click menus take two clicks to open a second submenu

### ISSUE THREAD

**Issue by smwcollege** [aberkow/a11y-menu#56]
This is a bug I've found with the click menus.

Here is my example menu setup:
- Toggle1
- - Submenu1
- Toggle2
- - Submenu2

Here is what happens:

1. Page loads, click toggle1: toggle1 gets focus class, submenu1 gets open class
2. Click toggle2: toggle1 loses focus class, submenu1 loses open class, toggle2 receives focus class, submenu2 _does not_ receive open class
3. Click toggle2 again: toggle2 receives focus class again, submenu2 receives open class

Here is a visual example: https://www.loom.com/share/2c524cd8b3a0477abf748cb30fa3ede0

**Comment by aberkow** [comment]
this should be resolved by #59 . @smwcollege can you check it out and confirm?

**Comment by smwcollege** [comment]
I can confirm the issue is fixed. Closing it out.
